### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MarkGod66** [xF4b3r/krunker.io-hack#15]
Krunker devs fixed the hack, can u update it?

**Comment by Tehchy** [comment]
Can't work on this till the end of the day sorry

**Comment by Tehchy** [comment]
But I will update it if possible

**Comment by Jytesh** [comment]
mod fixed by devs

**Comment by Tehchy** [comment]
I'm working on a fix now

**Comment by alamkhokhar** [comment]
Yeah, it's not loading anymore :/
Here's a screenshot:
![image](https://user-images.githubusercontent.com/33488649/48302926-6e9ed180-e4d1-11e8-86d0-88491ead8908.png)

**Comment by alamkhokhar** [comment]
It's not a virus right?

**Comment by ArmaanTornow** [comment]
Lmao no

**Comment by alamkhokhar** [comment]
It's not autoshooting m8

**Comment by ArmaanTornow** [comment]
u gotta turn on auto shoot, and its still buggy, u need to scope in for it to work

**Comment by ArmaanTornow** [comment]
just open an issue there if theres a problem 😉

**Comment by alamkhokhar** [comment]
Ok, just keep deleting ur comments cuz this isnt the place to chat lol also maybe krunker devs are watching lol o_0

**Comment by ArmaanTornow** [comment]
not krunker devs lol, its this aimbots devs, they prob dont want links to other hacks makes sense

**Comment by Tehchy** [comment]
Updated Enjoy
