### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by Jytesh** [xF4b3r/krunker.io-hack#18]
it was patched

**Comment by anon353249** [comment]
It does work, 17 hours ago the team updated the hacks to bypass the latest patch. You need to update the script. Click on this link to update the script manually. https://github.com/xF4b3r/krunker/raw/master/userscript.user.js

**Comment by Jytesh** [comment]
ok, thanks. Could you update it so that we can see the flags in the new gamemode(Points). Thank YOu

**Comment by Tehchy** [comment]
Faber is working on that part

**Comment by uwuber** [comment]
is it down again?

**Comment by xF4b3r** [comment]
flag added
