### ISSUE TITLE
I can not even aim myself... So annoying.

### ISSUE THREAD

**Issue by Rabitsta** [xF4b3r/krunker.io-hack#20]
It auto aims and fires, but it still won't let me aim myself. Please fix it.

**Comment by Tehchy** [comment]
That's because your using triggerbot

**Comment by Rabitsta** [comment]
To turn it off I do what?

**Comment by Tehchy** [comment]
Hit esc then click hacks and go down to autoaim and change to manual

**Comment by Rabitsta** [comment]
Where do I click esc

**Comment by Rabitsta** [comment]
On the game or...

**Comment by Rabitsta** [comment]
Never Mind... I figured it out. Thanks!
