### ISSUE TITLE
Not loading the page

### ISSUE THREAD

**Issue by matizzzz** [xF4b3r/krunker.io-hack#22]
i have updated everything to 2.14v on the script but the page is not loading

**Comment by Tehchy** [comment]
can you provide more details because i just loaded it up perfectly fine

**Comment by matizzzz** [comment]
is just white page

**Comment by Tehchy** [comment]
can you show me your developer console?

**Comment by matizzzz** [comment]
ok

**Comment by matizzzz** [comment]
hmm its loading now buts it is vannilla

**Comment by matizzzz** [comment]
![image](https://user-images.githubusercontent.com/45042520/48495067-e2294180-e837-11e8-8e65-6231b987c39c.png)

**Comment by Tehchy** [comment]
click console and then show me

**Comment by matizzzz** [comment]
the script?

**Comment by matizzzz** [comment]
![image](https://user-images.githubusercontent.com/45042520/48495289-5663e500-e838-11e8-96c5-3b9353edafc4.png)

**Comment by Tehchy** [comment]
That shows that the script isn't the issue. Could either be tamper monkey or your browser

**Comment by matizzzz** [comment]
ok
