### ISSUE TITLE
Patched 

### ISSUE THREAD

**Issue by Jytesh** [xF4b3r/krunker.io-hack#23]
It was patched by Krunk Devs , i am using latest version . 2.14.

**Comment by Tehchy** [comment]
As far as I can tell there wasn't any updated to krunker but I will check in a few

**Comment by Tehchy** [comment]
i just checked and its still not patched it must be something on your end

**Comment by Tehchy** [comment]
What browser and version of browser are you using?

**Comment by Jytesh** [comment]
Firefox Quantum

**Comment by Jytesh** [comment]
Just a white screen displays

**Comment by Jytesh** [comment]
Firefox Quantum 63.0 (64-bit)
