### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by Djtorg** [xF4b3r/krunker.io-hack#27]
aimbot is not always working and does not work unless you are zooming in/scope on a gun. but besides that when its working and I'm on a roll its great, I usually get 200 coins in 2 or 3 rounds

**Comment by Tehchy** [comment]
There is differently ainbot setting

**Comment by Djtorg** [comment]
what aimbot do you think is the best

**Comment by Tehchy** [comment]
Manual = Right click to track player
Trigger bot = Automatic player tracking and shooting
Quickscoper = Automatic player tracking and instant quickscope
Hip fire = Automatic player tracking when not aiming in

**Comment by Djtorg** [comment]
ok, that's why I was not doing so good on manual thanks!

**Comment by Djtorg** [comment]
sry for so many questions but for aimbot in the future for auto shooting can it switch guns when needing to be reloaded because I mostly die because of that
