### ISSUE TITLE
Aimbot Activation angle(read description) 

### ISSUE THREAD

**Issue by Miner1834** [xF4b3r/krunker.io-hack#30]
This means a menu that toggles the aimbot restriction angle(ex: 20 degrees, 30 degrees, etc.), which means that the aimbot will only activate if the cursor is within a certain angle of the cursor so people don't get mad when the aimbot spins you backwards to shoot them and they know we're hacking. 
 Another option would also be that the aimbot only works if the player is on screen. 

Also, the autoswitch should have toggle key :)

P.S. Good job on the hack xD

**Comment by Djtorg** [comment]
miner I don't know if this is just for me but where it says pro tip does it say like: Djtorg

**Comment by xF4b3r** [comment]
@Miner1834 done, there's an option now. make sure to reinstall the script
![image](https://user-images.githubusercontent.com/37834714/49186197-3407b680-f364-11e8-8437-5fd546f65588.png)
