### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by IAmAHumanIThink** [xF4b3r/krunker.io-hack#32]
I've been using this script, but all of a sudden Krunker just said "Connecting..." And it just doesn't stop saying that.
<img width="2033" alt="screen shot 2018-11-23 at 5 37 22 pm" src="https://user-images.githubusercontent.com/43094874/48961904-a6ccf800-ef46-11e8-9c82-f1dee3332f33.png">

**Comment by IAmAHumanIThink** [comment]
And here is the console:
<img width="1883" alt="screen shot 2018-11-23 at 5 35 46 pm" src="https://user-images.githubusercontent.com/43094874/48961905-b5b3aa80-ef46-11e8-819b-97acbfa8e9d2.png">

**Comment by xF4b3r** [comment]
works fine for me, do you have the latest version installed?

**Comment by IAmAHumanIThink** [comment]
Yes, I do.

**Comment by IAmAHumanIThink** [comment]
Ok, so just now I opened Krunker without the hack and it did the same thing. So, I guess it's a problem with my computer. I'm going to restart and pray that it works.

**Comment by IAmAHumanIThink** [comment]
And um so I restarted my computer and chrome. No luck, so I guess I just can't ever play krunker...
