### ISSUE TITLE
Speed Hack Speed Changer Slider 

### ISSUE THREAD

**Issue by Miner1834** [xF4b3r/krunker.io-hack#42]
It would be awesome if you could include a slider for speed hacks. Also, could you make it so you don't hit the ground quicker after jumping when enabled, though? At first, I thought it was fake and just a time scale tweak, but then I remembered it was online and the other people were moving slower without speed hacks. Anyway, please include a slider to we can speed around way faster.

**Comment by Tehchy** [comment]
It indeed is a time scale tweak but somehow worked out. This is the max limit you can go without rubber banding
