### ISSUE TITLE
Time Frame

### ISSUE THREAD

**Issue by Jytesh** [xF4b3r/krunker.io-hack#45]
The time taken to load the krunker.io page in the first try is too much

Time taken without tampermonkey on = 0.2 Secs
Time taken with tampermonkey on = 12 Secs
I timed it with an insystem app.
Pls do fix this. Also krunker mods have announced that within 2 days all hackers will be banned and all hacks removed. So pls be careful. Also we can can datamine the files now and after the update configure the . difference and upgrade ur mod. 

Thanks for the best mod ever

**Comment by Tehchy** [comment]
Bro you do know ive compared every update for the last 5 months? Also it takes that long because it has to reload fetch the page
