### ISSUE TITLE
Anti-Cheat

### ISSUE THREAD

**Issue by Jytesh** [xF4b3r/krunker.io-hack#52]
Now you cant login if you have this hack on.Make code private as i think mods are accesing this code.

**Comment by Tehchy** [comment]
Please make sure your on 3.15 because I removed the hack check

**Comment by 1029384756102938471** [comment]
even after the 3.15 hack check the aimbot and other things don't work, please fix this and tell me when you are done

**Comment by Usernameisalreadytak** [comment]
The hack tab is just gone from the top right. Can you fix this?

**Comment by xF4b3r** [comment]
update the script, should be working now
